name: fiveamfilms
favicon: null
layout_spectrum: 0.50586
typography_spectrum: 0.32747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1919'
    - '#ffffff'
    - '#d2d1d1'
    - '#6c6b6b'
    - '#a8a8a8'
  brandStrength: 0.9982101824134588
  lightness: 0.703357960563153
  saturation: 0.7451070884708315
  rhythmicContrast: 0.38127470458857715
purpose: []
